# Generated by Django 5.2.6 on 2025-10-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='artikul_number',
            new_name='article_number',
        ),
    ]
